version: '3'

services:
  app:
    build: ./
    container_name: marketplacePriceParserAppContainer
    env_file:
      - .env
      - .env.mongo
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: always
  
  db:
    image: mongo
    container_name: marketplacePriceParserMongoContainer
    env_file:
      - .env.mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '2222:27017'


volumes:
  app_volume:
  mongo_data: